{
 "title": "CircleGuard Overview",
 "panels": [
  {
   "title": "Servicios UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(up)", "legendFormat": "up" }
   ]
  },
  {
   "title": "Promociones de estado",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(circleguard_promotions_total[5m])",
     "legendFormat": "promotions/s"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}