apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: circleguard
resources:
  - namespace.yaml
  - rbac/service-accounts.yaml
  - rbac/roles.yaml
  - rbac/role-bindings.yaml
  - config/configmaps.yaml
  - config/secrets.example.yaml
  - infrastructure/postgres-init-configmap.yaml
  - infrastructure/postgres.yaml
  - infrastructure/neo4j.yaml
  - infrastructure/redis.yaml
  - infrastructure/kafka.yaml
  - services/circleguard-auth-service.yaml
  - services/circleguard-identity-service.yaml
  - services/circleguard-promotion-service.yaml
  - services/circleguard-notification-service.yaml
  - services/circleguard-form-service.yaml
  - services/circleguard-file-service.yaml
  - services/circleguard-gateway-service.yaml
  - services/circleguard-dashboard-service.yaml
  - observability/prometheus.yaml
  - observability/grafana.yaml
  - observability/jaeger.yaml
  - observability/fluent-bit.yaml
  - ingress.yaml
