apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-auth-service
  namespace: circleguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-identity-service
  namespace: circleguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-promotion-service
  namespace: circleguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-notification-service
  namespace: circleguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-form-service
  namespace: circleguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-file-service
  namespace: circleguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-gateway-service
  namespace: circleguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-dashboard-service
  namespace: circleguard
